// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvvcSx1BdfmcIYrX9KJ_icgTGSlxKneLI',
    appId: '1:55880878987:web:c7d16297d1e51dc6a3bd8e',
    messagingSenderId: '55880878987',
    projectId: 'booking-apps-ac3b9',
    authDomain: 'booking-apps-ac3b9.firebaseapp.com',
    storageBucket: 'booking-apps-ac3b9.appspot.com',
    measurementId: 'G-JRRLCES2CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhrGlADmc7Li2XgaWA_YDcyS8OtOsP1jY',
    appId: '1:55880878987:android:31d98cee6805b5a2a3bd8e',
    messagingSenderId: '55880878987',
    projectId: 'booking-apps-ac3b9',
    storageBucket: 'booking-apps-ac3b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD55NBUwefCi1yaGHxq3yD1ikokHu-9KNI',
    appId: '1:55880878987:ios:e555605b44dfe5e1a3bd8e',
    messagingSenderId: '55880878987',
    projectId: 'booking-apps-ac3b9',
    storageBucket: 'booking-apps-ac3b9.appspot.com',
    iosBundleId: 'com.example.bookingApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD55NBUwefCi1yaGHxq3yD1ikokHu-9KNI',
    appId: '1:55880878987:ios:e555605b44dfe5e1a3bd8e',
    messagingSenderId: '55880878987',
    projectId: 'booking-apps-ac3b9',
    storageBucket: 'booking-apps-ac3b9.appspot.com',
    iosBundleId: 'com.example.bookingApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvvcSx1BdfmcIYrX9KJ_icgTGSlxKneLI',
    appId: '1:55880878987:web:dfb23788998347e2a3bd8e',
    messagingSenderId: '55880878987',
    projectId: 'booking-apps-ac3b9',
    authDomain: 'booking-apps-ac3b9.firebaseapp.com',
    storageBucket: 'booking-apps-ac3b9.appspot.com',
    measurementId: 'G-VLBBH7V354',
  );
}
